import type { Metadata } from 'next';
import './globals.css';
import { inter } from './lib/fonts';

export const metadata: Metadata = {
  title: 'LMS Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  );
}
