import type { Metadata } from 'next';
import './globals.css';
import { inter } from './lib/fonts';
import { Toaster } from '@/app/components/ui/sonner';
import { ThemeProvider } from './theme-provider';

export const metadata: Metadata = {
  title: 'LMS Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
