import type { Metadata } from 'next';
import './globals.css';
import { inter } from './lib/fonts';
import { Toaster } from '@/app/components/ui/sonner';

export const metadata: Metadata = {
  title: 'LMS Platform',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
